
services:
  zone-service:
    build: .
    ports:
      - 8082:8082
    env_file:
      - .env
    
    networks:
      - iaas-firecracker-network

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zone_service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iaas-firecracker-network

volumes:
  postgres_data:

networks:
  iaas-firecracker-network:
    external: true
    name: iaas-firecracker-network  # Replace with actual network name